import { Routes } from '@angular/router';
import { MyAssets } from '../shared/components/ess/my-assets/my-assets';
import { ServiceFile } from '../shared/components/ess/service-file/service-file';
import { ReportingsAttendance } from '../shared/components/ess/reportings-attendance/reportings-attendance';
import { GetEmployeeInfo } from '../shared/components/ess/get-employee-info/get-employee-info';
import { EmployeeAttendance } from '../shared/components/ess/employee-attendance/employee-attendance';
import { EssDashboard } from '../shared/components/ess/ess-dashboard/ess-dashboard';
import { AttendanceRegularization } from '../shared/components/ess/attendance-regularization/attendance-regularization';
import { MonthlyAttendanceCalendar } from '../shared/components/ess/monthly-attendance-calendar/monthly-attendance-calendar';
import { LeaveApplication } from '../shared/components/ess/leave-application/leave-application';
import { ApplyShortLeave } from '../shared/components/ess/apply-short-leave/apply-short-leave';
import { FinalAttendance } from '../shared/components/ess/final-attendance/final-attendance';
import { EmployeeResignation } from '../shared/components/ess/employee-resignation/employee-resignation';
import { ExitInterview } from '../shared/components/ess/exit-interview/exit-interview';
import { ExpenseManagement } from '../shared/components/ess/expense-management/expense-management';
import { PerformanceManagement } from '../shared/components/ess/performance-management/performance-management';
import { Probation } from '../shared/components/ess/probation/probation';
import { Ticket } from '../shared/components/ess/ticket/ticket';

export const essRoutes: Routes = [
  { path: '', redirectTo: 'ess-dashboard', pathMatch: 'full' },
  { path: 'ess-dashboard', component: EssDashboard },
  { path: 'my-assets', component: MyAssets },
  { path: 'service-file', component: ServiceFile },
  { path: 'reportings-attendance', component: ReportingsAttendance },
  { path: 'get-employee-info', component: GetEmployeeInfo },
  { path: 'employee-attendance', component: EmployeeAttendance },
  { path: 'attendance-regularization', component: AttendanceRegularization },
  { path: 'monthly-attendance-calendar', component: MonthlyAttendanceCalendar },
  { path: 'leave-application', component: LeaveApplication },
  { path: 'apply-short-leave', component: ApplyShortLeave },
  { path: 'final-attendance', component: FinalAttendance },
  { path: 'employee-resignation', component: EmployeeResignation },
  { path: 'exit-interview', component: ExitInterview },
  { path: 'expense-management', component: ExpenseManagement },
  { path: 'performance-management', component: PerformanceManagement },
  { path: 'probation', component: Probation },
  { path: 'ticket', component: Ticket },
];
